# Site settings
title: ccslience
subtitle: ccslience blog
keywords: ccslience
description: 我梦扬州，便想到扬州梦我。幸会。微信公众号：oukohou.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ccslience.oukohou.wang/" # 你的域名
page_no_title: "ccslience's blog" # 文章无标题时默认显示内容
beian: # "备案号"
author: ccslience
email: oukohou@outlook.com

# Build settings
permalink: /:year/:month/:day/:title/
exclude: ["README.md", "changelog.md", "server", "tools", "Pipfile"]
plugins: [jekyll-paginate]

# always get github's error email saying redcarpet is not supported,
# so change it to kramdown.
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

#markdown: redcarpet
#redcarpet:
#    extensions: ["fenced_code_blocks",
#                 "tables",
#                 "highlight",
#                 "strikethrough",
#                 "no_intra_emphasis",
#                 "with_toc_data"]

# Pageinate settings
paginate: 8 # 分页大小
paginate_path: "page/:num/"

# Search settings
baidu_search: true
google_search: # true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 标签
    directory: tags/
    icon: icon-tags
  - page: 留言
    directory: guestbook/
    icon: icon-guestbook
  - page: 关于
    directory: about/
    icon: icon-about
#  - page: 订阅
#    directory: feed.xml
#    icon: icon-rss

# Link settings
links: # 友情链接
  - title: oukohou's github
    url: https://github.com/oukohou
  - title: ccslience's github
    url: https://github.com/ccslience
#  - title:
#    url: http://jekyllcn.com/
  - title: Jekyll 博客系统
    url: http://jekyllcn.com/



# Google Analytics
ga_track_id: 'UA-126058460-1'            # Format: UA-xxxxxx-xx
ga_domain: www.ccslience.oukohou.wang              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Valine settings.
valine:
  enable: true
  app_id:  259mVn1W4109smfktjL08NJQ-gzGzoHsz
  app_key: JiehnrXtKpSjfIhnTkTOliSg
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  visitor: true
  avatar: retro
  placeholder: say something~~\n - 昵称 为你所要显示的评论的ID；\n - 邮箱 只有后台可见，仅供讨论过程中是否需要交流邮件而设置，请放心填写;\n - 网址 为你的评论的昵称的超链接。\n当然，以上都可以不写，评论依然会显示……
  guest_info: nick,mail,link
  pageSize: 10


# Code hub settings
codehub: # 代码仓库
  - title: Github
    url: https://github.com/ccslience
